# docker-compose.yml
version: '3.8'

services:
  jasperserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=jasperserver
      - DB_USERNAME=jasperuser
      - DB_PASSWORD=jasperpassword
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=jasperserver
      - POSTGRES_USER=jasperuser
      - POSTGRES_PASSWORD=jasperpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
